# Neural Rerank Engine: demo

The same two-stage pipeline as the API, on the **BEIR SciFact** corpus (5,183 scientific abstracts):

1. **Stage 1, hybrid retrieval**: BM25 (keywords) + FAISS (embeddings of `all-MiniLM-L6-v2`), merged with
   Reciprocal Rank Fusion (RRF). Fast, returns 50 candidates.
2. **Stage 2, reranking**: the cross-encoder `ms-marco-MiniLM-L-6-v2` reads each (query, abstract) pair and
   re-sorts the 50 candidates. Slow but more precise.

This notebook shows **what reranking changes** on a few queries and **where the time goes**.
It does not measure retrieval quality (no nDCG/MRR): see the Limitations section of `docs/MLOPS_GUIDE.md`.

Prerequisite: the indices exist (`make index`) and the notebook runs with the project's venv.

In [1]:
import statistics
import time
import warnings

import pandas as pd

from rerank_engine.config import get_settings
from rerank_engine.engine import load_engine

pd.set_option("display.max_colwidth", 90)
warnings.filterwarnings("ignore")  # hide library warnings (urllib3/LibreSSL, tqdm) in the outputs

## 1. Load the engine
Same function as the API at startup: both models and both indices are loaded into memory once.
`INDEX_DIR` defaults to `data/indices`, relative to the repository root, so the notebook moves there first.

In [2]:
import os

if os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")

settings = get_settings()
start = time.perf_counter()
engine = load_engine(settings)
print(f"Engine loaded in {time.perf_counter() - start:.1f}s (candidates sent to the reranker: {settings.top_k})")

Engine loaded in 11.8s (candidates sent to the reranker: 50)

## 2. Before / after reranking
For each query: the top 3 of stage 1 alone (`rerank=False`, score = RRF) next to the top 3 after the
cross-encoder (`rerank=True`, score = cross-encoder logit). Same 50 candidates, different order.

In [3]:
def top3(query):
    hybrid = engine.search(query, top_k=3, rerank=False)
    reranked = engine.search(query, top_k=3, rerank=True)
    rows = []
    for rank in range(3):
        rows.append({
            "rank": rank + 1,
            "hybrid only": hybrid[rank]["text"][:90],
            "hybrid + rerank": reranked[rank]["text"][:90],
        })
    return pd.DataFrame(rows).set_index("rank")

query = "statins lower LDL cholesterol"
print(query)
top3(query)

statins lower LDL cholesterol

,hybrid only,hybrid + rerank
rank,,
1,A Century of Cholesterol and Coronaries: From Plaques to Genes to Statins One-fourth o...,How to control residual cardiovascular risk despite statin treatment: focusing on HDL-...
2,Pleiotropic effects of statins. Statins are potent inhibitors of cholesterol biosynthe...,A Century of Cholesterol and Coronaries: From Plaques to Genes to Statins One-fourth o...
3,"Serum plant and other noncholesterol sterols, cholesterol metabolism and 22-year morta...",Pleiotropic effects of statins. Statins are potent inhibitors of cholesterol biosynthe...

In [4]:
query = "vitamin D deficiency increases the risk of multiple sclerosis"
print(query)
top3(query)

vitamin D deficiency increases the risk of multiple sclerosis

,hybrid only,hybrid + rerank
rank,,
1,[Vitamin D and latitude as environmental factors in multiple sclerosis]. Multiple scle...,[Vitamin D and latitude as environmental factors in multiple sclerosis]. Multiple scle...
2,"Vitamin D: The ""sunshine"" vitamin. Vitamin D insufficiency affects almost 50% of the p...","Vitamin D: The ""sunshine"" vitamin. Vitamin D insufficiency affects almost 50% of the p..."
3,Estimation of optimal serum concentrations of 25-hydroxyvitamin D for multiple health ...,Low serum vitamin D is associated with high risk of diabetes in Korean adults. Vitamin...

In [5]:
query = "sleep deprivation impairs memory consolidation"
print(query)
top3(query)

sleep deprivation impairs memory consolidation

,hybrid only,hybrid + rerank
rank,,
1,"Melatonin and the circadian regulation of sleep initiation, consolidation, structure, ...",A specific amyloid-β protein assembly in the brain impairs memory Memory function ofte...
2,Mindfulness meditation and improvement in sleep quality and daytime impairment among o...,"Melatonin and the circadian regulation of sleep initiation, consolidation, structure, ..."
3,Cognitive behavioral therapy vs zopiclone for treatment of chronic primary insomnia in...,"Interactions between sleep, circadian function, and glucose metabolism: implications f..."

## 3. Where the time goes
The two stages are timed separately on the 8 example queries of `scripts/load_test.py`, one query at a time,
after one warm-up query. The numbers depend on the machine: run the notebook again to get yours.

In [6]:
QUERIES = [
    "vitamin D deficiency increases the risk of multiple sclerosis",
    "smoking is associated with lung cancer",
    "aspirin reduces the risk of cardiovascular events",
    "obesity is a risk factor for type 2 diabetes",
    "antibiotics are effective against viral infections",
    "statins lower LDL cholesterol",
    "sleep deprivation impairs memory consolidation",
    "BRCA1 mutations increase breast cancer risk",
]

engine.search(QUERIES[0])  # warm-up, not counted

stage1_ms, stage2_ms = [], []
for q in QUERIES:
    t0 = time.perf_counter()
    candidates = engine.retriever.search(q, k=settings.top_k)
    t1 = time.perf_counter()
    engine.reranker.rerank(q, candidates, top_n=10)
    t2 = time.perf_counter()
    stage1_ms.append((t1 - t0) * 1000)
    stage2_ms.append((t2 - t1) * 1000)

timing = pd.DataFrame({
    "stage": ["1. hybrid retrieval (BM25 + FAISS + RRF)", "2. cross-encoder rerank (50 pairs)"],
    "median (ms)": [round(statistics.median(stage1_ms), 1), round(statistics.median(stage2_ms), 1)],
})
share = statistics.median(stage2_ms) / (statistics.median(stage1_ms) + statistics.median(stage2_ms))
print(f"Reranking = {share:.0%} of the median search time")
timing

Reranking = 96% of the median search time

                                      stage  median (ms)
0  1. hybrid retrieval (BM25 + FAISS + RRF)         21.2
1        2. cross-encoder rerank (50 pairs)        493.9

## Takeaways
- Reranking changes the order of the same 50 candidates: the cross-encoder reads the query and the abstract
  together, while stage 1 only compares keywords and separate embeddings.
- Different is not always better: on "sleep deprivation impairs memory consolidation" the reranker puts an
  amyloid-β / memory paper first, which is arguably less relevant than stage 1's sleep papers. The cross-encoder
  was trained on MS MARCO (web questions), not on scientific claims. Three queries prove nothing either way:
  this is why a real quality metric is needed (last point).
- Almost all of the time is spent in the cross-encoder. Ways to go faster: fewer candidates (`TOP_K`),
  an ONNX / quantized model, a GPU, or more pods (see the load tests in the README).
- Next step: measure quality with SciFact's **test** queries and relevance judgments (qrels), e.g. nDCG@10,
  with and without reranking.